
HUNDRED = 100

MAX_CONTACT_NUMBER_LENGTH = 15

MIN_PRODUCT_WEIGHT = 0
MAX_PRODUCT_WEIGHT = 25
PRODUCT_WEIGHT_MAX_DIGIT = 5
PRODUCT_WEIGHT_DECIMAL_PLACES = 2

CUSTOMER_NAME_MAX_LENGTH = HUNDRED
PRODUCT_NAME_MAX_LENGTH = HUNDRED

MAX_ORDER_NUMBER = 10

MIN_ORDER_ITEM_QUANTITY = 1
ORDER_ADDRESS_MAX_LENGTH = 500

MAX_CUMULATIVE_WEIGHT = 150