version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "core.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
