# Generated by Django 5.0 on 2023-12-12 11:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
                ('contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Contact number must contain only numeric characters.', regex='^\\d(1, {15})$')], verbose_name='Contact Number')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
    ]
