# Generated by Django 4.2.4 on 2023-12-14 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Contact number must contain only numeric characters.', regex='^\\d{1,15}$')], verbose_name='Contact Number'),
        ),
    ]
