---
openapi: 3.0.0
info:
  title: E-commerce API
  description: ecommerce api using drf
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 1.0.0
servers:
- url: https://app.swaggerhub.com/apis-docs/Sahal-P/Fero.ai/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://app.swaggerhub.com/apis-docs/Sahal-P/Fero.ai/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://127.0.0.1:8000
  description: Django E-commerce API
tags:
- name: customers
  description: Operations related to customers
- name: products
  description: Operations related to products
- name: orders
  description: Operations related to orders
paths:
  /api/customers/:
    get:
      tags:
      - customers
      summary: Retrieve a list of customers
      operationId: listCustomers
      responses:
        "200":
          description: A list of customers
    post:
      tags:
      - customers
      summary: Create a new customer
      operationId: createCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        "201":
          description: Customer created successfully
        "400":
          description: Bad request
  /api/products/:
    get:
      tags:
      - products
      summary: Retrieve a list of products
      operationId: listProducts
      responses:
        "200":
          description: A list of products
    post:
      tags:
      - products
      summary: Create a new product
      operationId: createProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "201":
          description: Product created successfully
        "400":
          description: Bad request
  /api/orders/:
    get:
      tags:
      - orders
      summary: Retrieve a list of orders
      operationId: listOrders
      responses:
        "200":
          description: A list of orders
    post:
      tags:
      - orders
      summary: Create a new order
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        "201":
          description: Order created successfully
        "400":
          description: Bad request
components:
  schemas:
    Customer:
      required:
      - contact_number
      - email
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        contact_number:
          type: string
        email:
          type: string
          format: email
    Product:
      required:
      - name
      - weight
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        weight:
          type: number
          format: double
    Order:
      required:
      - address
      - customer
      - order_items
      type: object
      properties:
        id:
          type: integer
          format: int64
        order_number:
          type: string
        customer:
          $ref: '#/components/schemas/Customer'
        order_date:
          type: string
          format: date
        address:
          type: string
        order_items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
    OrderItem:
      required:
      - product
      - quantity
      type: object
      properties:
        id:
          type: integer
          format: int64
        order:
          $ref: '#/components/schemas/Order'
        product:
          $ref: '#/components/schemas/Product'
        quantity:
          type: integer
