# Generated by Django 5.0 on 2023-12-12 11:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms.', max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Weight must be a positive decimal.'), django.core.validators.MaxValueValidator(25, message='Weight must not be more than 25kg.')], verbose_name='Weight')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
